version: "3.6"

services:
  server:
    build:
      context: ./server/
    command: npm run dev
    volumes:
      - ./server/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development

  client:
    image: node:10
    command: bash
    working_dir: /app/client
    command: yarn start
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
    links:
      - server    
    depends_on:
      - server      
    ports:
      - "3000:3000"      
    environment:
      server: http://server:8090
      ENVIRONMENT_NAME: dev  

volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
