version: "3.6"

services:
  bare: &app
    image: node:10
    working_dir: /app/
    command: yarn dev
    volumes:
      - ./:/app/
      - yarn-cache:/usr/local/share/.cache/yarn/v2
      - node_modules:/app/node_modules/
    environment:
      DATABASE_HOST: ${DATABASE_HOST-pg}
      DATABASE_NAME: ${DATABASE_NAME-reward-service-default}
      DATABASE_USERNAME: ${DATABASE_USERNAME-reward-service}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD-super-secure}

  full:
    <<: *app
    ports:
      - 8090:8090

volumes:
  node_modules: {}
  yarn-cache: {
    external: true
  }
